<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.11.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MentalHealthApp.Application\MentalHealthApp.Application.csproj" />
    <ProjectReference Include="..\MentalHealthApp.Infrastructure\MentalHealthApp.Infrastructure.csproj" />
    <ProjectReference Include="..\MentalHealthApp.fx\MentalHealthApp.fx.csproj" />
  </ItemGroup>

</Project>
