<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MentalHealthApp.Domain\MentalHealthApp.Domain.csproj" />
    <ProjectReference Include="..\MentalHealthApp.fx\MentalHealthApp.fx.csproj" />
    <ProjectReference Include="..\MentalHealthApp.Application\MentalHealthApp.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.11.0" />
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.74.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.7.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
